### ISSUE TITLE
import FP or require FP retun a empty object

### ISSUE THREAD

**Issue by Gi972** [functional-promises/functional-promises#47]
Hello,

I want try your libray , but after make npm install functional-promise,
import or require return a empty object.

I make the test on codesandbox.io ,  stackblitz.com and on I create a project via npm (create-react-app)

I miss something ?

Thanks

**Comment by justsml** [comment]
I'll try it and post examples on one of those sites.


Thanks for the heads-up.

**Comment by Gi972** [comment]
Thanks,

Your work  on this pattern seems so great. Simple and easy to use . 👍

**Comment by justsml** [comment]
Thanks @Gi972  that means a lot!!! 😊 😸 

I got it fixed in v1.6.3+.

Turns out I didn't know how to bundle for several targets: browser, nodejs and ES6 Modules.

Check out this React example: 

* [Combined validation + setState in an event handler](https://stackblitz.com/edit/react-functional-promises?file=index.js)
* [With a custom composition helper (see `pipeInput`)](https://stackblitz.com/edit/react-functional-promises-v2?file=index.js)

I'll add a more real-world example (that checks for email/username availability in the pipeline) when I can find some time.

Overall the bundle sizes came down even more 💥 

The polyfilled minified+gzipped bundle is 1Kb lighter, at around 3Kb. 
And the total lines of code decreased by ~20. 
Now closer to 370 LoC total in original source.

# 🚀
